### ISSUE TITLE
css bug when adding img

### ISSUE THREAD

**Issue by akissz** [luizbills/wp-tweaks#15]
There is a little css bug in your plugin when you add a image to the custom admin footer text. You would not normally add a image but I was testing your plugin and see when you add a image tag the image covers the save button on the bottom of the page so you can't make future changes/saves unless you hide the image with force; or delete the image manually from server.

While I am writing. To me it makes sense to please add a complete site footer edit feature too to edit site wide classes like "site-info", "site-branding", "site-footer", to edit the whole site not just the admin footer. Or maybe a simple class or id box where you type the name of css class/id and a box under that that you can enter text or code to replace with. I like your plugin a lot.

**Comment by luizbills** [comment]
This is not a bug of the plugin, it's a CSS from WordPress.
![image](https://user-images.githubusercontent.com/1798830/91661791-8e432780-eab4-11ea-92f2-a92fade75128.png)

Btw, my plugin don't includes any custom CSS.

**Comment by luizbills** [comment]
If you need put a big image there, add this CSS in your wp-admin
```css
#wpfooter { position: static }
```

**Comment by luizbills** [comment]
> While I am writing. To me it makes sense to please add a complete site footer edit feature too to edit site wide classes like "site-info", "site-branding", "site-footer", to edit the whole site not just the admin footer. Or maybe a simple class or id box where you type the name of css class/id and a box under that that you can enter text or code to replace with. I like your plugin a lot.

I want to keep the scope of the plugin simple. That field for changing the footer is just for you to use to put some useful information like support link or phone.
