### ISSUE TITLE
Multisite Bug

### ISSUE THREAD

**Issue by akissz** [luizbills/wp-tweaks#19]
When you enable the plugin on a network multisite wordpress configuration. The options are all on but not visible to change even on the main site. So you can not use the plugin editor due to the option "Disallow file edit" being enabled by default which is a problem for the main site. So can you make the plugin show settings for the main site on a network multisite wordpress configuration. Please!

Its not a big problem. But it is a little strange. :)

**Comment by luizbills** [comment]
Hi @akissz 
I tried to reproduce this bug in my local workspace but it worked perfectly. I configured each site without any problems.

**Comment by akissz** [comment]
> Hi @akissz
> I tried to reproduce this bug in my local workspace but it worked perfectly. I configured each site without any problems.

Maybe you didn't understand this bug. This bug is not about the "sites" added. The point is the setting to edit files should be enabled for the main admin account; meaning the super user should be able to edit files, or the feature should be available to turn on the feature.

**Comment by luizbills** [comment]
Oh my bad, I I understand now. With the option disabled only the multisite panel can edit files (no child will be able to edit). So you can just leave it disabled or put the following snippet in your theme's `functions.php`:

```php
add_action( 'init', function ( $flag ) {
	if ( current_user_can( 'install_plugins' ) ) {
		remove_action( 'init', 'wp_tweaks_disallow_file_edit' );
	}
}, 5 );
```
